-- Create the site_config table to store dynamic website settings
CREATE TABLE IF NOT EXISTS site_config (
  id bigint PRIMARY KEY generated by default as identity,
  
  -- Store announcements as a JSON string array e.g. '["Sale 1", "Sale 2"]'
  notification_text text DEFAULT '[]',
  
  -- Toggle for the announcement bar
  notification_enabled boolean DEFAULT true,
  
  -- Store hero image URLs as a JSON string array e.g. '["/img1.png", "/img2.png"]'
  hero_images text DEFAULT '[]',
  
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Insert the default configuration row (Row ID 1) if it doesn't exist
INSERT INTO site_config (id, notification_text, hero_images, notification_enabled)
VALUES (
    1, 
    '["Welcome to Ritzee!", "Free Shipping on Orders Over $100"]',
    '["/hero-genz-1.png", "/hero-genz-2.png"]',
    true
)
ON CONFLICT (id) DO NOTHING;

-- Enable Row Level Security (RLS)
ALTER TABLE site_config ENABLE ROW LEVEL SECURITY;

-- Policy: Allow everyone (anonymous users) to READ the config
-- This is required for the homepage to load the hero images/announcements
CREATE POLICY "Enable read access for all users" ON site_config
    FOR SELECT USING (true);

-- Policy: Allow everyone to UPDATE (TEMPORARY FOR DEVELOPMENT)
-- Since we haven't implemented Admin Auth yet, we allow public updates to this table
-- so your Admin Dashboard works immediately.
-- TODO: Restrict this to authenticated admins later.
CREATE POLICY "Enable update access for all users" ON site_config
    FOR UPDATE USING (true);

-- Policy: Allow insert (in case row is deleted)
CREATE POLICY "Enable insert access for all users" ON site_config
    FOR INSERT WITH CHECK (true);
